"""Manifest and inventory primitives for DGX Spark benchmarks."""

from .inventory import (
    DockerImage,
    HuggingFaceSnapshot,
    Inventory,
    InventoryError,
    ModelAvailability,
    OllamaModel,
    assess_model_availability,
    collect_inventory,
    discover_docker_images,
    discover_huggingface_snapshots,
    discover_ollama_models,
    discover_ollama_version,
    inventory_to_dict,
)
from .manifest import (
    CaseSpec,
    ManifestError,
    ModelSpec,
    SuiteSpec,
    load_models,
    load_suite,
    validate_case,
    validate_model,
    validate_models,
    validate_suite,
)

__all__ = [
    "CaseSpec",
    "DockerImage",
    "HuggingFaceSnapshot",
    "Inventory",
    "InventoryError",
    "ManifestError",
    "ModelAvailability",
    "ModelSpec",
    "OllamaModel",
    "SuiteSpec",
    "assess_model_availability",
    "collect_inventory",
    "discover_docker_images",
    "discover_huggingface_snapshots",
    "discover_ollama_models",
    "discover_ollama_version",
    "inventory_to_dict",
    "load_models",
    "load_suite",
    "validate_case",
    "validate_model",
    "validate_models",
    "validate_suite",
]
